//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainInfoTable
    {
        public int ID { get; set; }
        public int idLesson { get; set; }
        public int idClassroom { get; set; }
        public int idTeacher { get; set; }
        public int idHeadOfTheDepartament { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual HeadOfTheDepartament HeadOfTheDepartament { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
